"""Added multi-currency support to Budget model

Revision ID: 891a4159a05c
Revises: 8d8d5b06cbd6
Create Date: 2024-08-22 18:19:58.535005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891a4159a05c'
down_revision = '8d8d5b06cbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
