"""Added budget tracking and multi-currency features

Revision ID: 8d8d5b06cbd6
Revises: 0608386134c8
Create Date: 2024-08-22 18:08:00.932582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8d5b06cbd6'
down_revision = '0608386134c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default = 'USD'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
